'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Examen

    Partial Public Class ListaAirbnb
        Public Property IdLocal As Integer
        Public Property DescripcionCabina As String
        Public Property IdDueno As Integer
        Public Property NombreDueno As String
        Public Property TipoCuarto As String
        Public Property Moneda As String
        Public Property Precio As Short
        Public Property NochesMinimas As Byte
        Public Property NumeroReviews As Byte
        Public Property ReviewsPorMes As Double
        Public Property habitables365 As Short
        Public Property Ciudad As String
        Public Property Estado As String
        Public Property Pais As String
    
    End Class

End Namespace
